#!/bin/bash

alias tarc='tar -cvzf'
alias tarx='tar -xvzf'
alias ls='ls -l -h --color=auto --group-directories-first'
alias updt='sudo apt update && sudo apt upgrade && sudo apt autopurge && sudo apt clean && sudo apt autoclean'
alias install='sudo apt install'
alias purge='sudo apt purge'
alias search='apt search'

alias fetch='screenfetch'



alias playlist='mpv --no-video --keep-open=no --shuffle'
alias xo="xdg-open"
alias convpdf='convert ./* output.pdf'



alias pt='sudo powertop'
alias ht='sudo htop'

alias slp='systemctl suspend'


export EDITOR='kate'
